// <auto-generated />
using System;
using MediCore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCore.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629124615_ConfermaPresenzaPaziente")]
    partial class ConfermaPresenzaPaziente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MediCore.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PazienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ruolo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("PazienteId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Fattura", b =>
                {
                    b.Property<Guid>("FatturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PazienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrenotazioneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("FatturaId");

                    b.HasIndex("PazienteId");

                    b.HasIndex("PrenotazioneId")
                        .IsUnique();

                    b.ToTable("Fatture");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServizioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specializzazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MedicoId");

                    b.HasIndex("ServizioId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Medici");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Notifica", b =>
                {
                    b.Property<Guid>("NotificaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Canale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinatarioUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Letta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RiferimentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatoInvio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("NotificaId");

                    b.HasIndex("DestinatarioUserId");

                    b.HasIndex("RiferimentoId", "Tipo")
                        .IsUnique()
                        .HasFilter("\"RiferimentoId\" IS NOT NULL");

                    b.ToTable("Notifiche");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Paziente", b =>
                {
                    b.Property<Guid>("PazienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PazienteId");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pazienti");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prenotazione", b =>
                {
                    b.Property<Guid>("PrenotazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfermataDalPaziente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PazienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrenotazioneId");

                    b.HasIndex("PazienteId");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasFilter("\"Stato\" <> 2");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prescrizione", b =>
                {
                    b.Property<Guid>("PrescrizioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosi")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurataGiorni")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Monitoraggio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificaInviata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OriginAssistita")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PazienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrescrizioneId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PazienteId");

                    b.ToTable("Prescrizioni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prestazione", b =>
                {
                    b.Property<Guid>("PrestazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServizioId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrestazioneId");

                    b.HasIndex("ServizioId");

                    b.ToTable("Prestazioni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Referto", b =>
                {
                    b.Property<Guid>("RefertoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenuto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrenotazioneId")
                        .HasColumnType("TEXT");

                    b.HasKey("RefertoId");

                    b.HasIndex("PrenotazioneId")
                        .IsUnique();

                    b.ToTable("Referti");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.RigaPrescrizione", b =>
                {
                    b.Property<Guid>("RigaPrescrizioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Farmaco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Posologia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrescrizioneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("RigaPrescrizioneId");

                    b.HasIndex("PrescrizioneId");

                    b.ToTable("RighePrescrizione");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Servizio", b =>
                {
                    b.Property<Guid>("ServizioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ServizioId");

                    b.ToTable("Servizi");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOraFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOraInizio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("TEXT");

                    b.HasKey("SlotId");

                    b.HasIndex("TurnoId", "DataOraInizio")
                        .IsUnique();

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Tariffa", b =>
                {
                    b.Property<Guid>("TariffaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrestazioneId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TariffaId");

                    b.HasIndex("PrestazioneId", "Regime")
                        .IsUnique();

                    b.ToTable("Tariffe");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Turno", b =>
                {
                    b.Property<Guid>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataSlotMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiornoSettimana")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrestazioneId")
                        .HasColumnType("TEXT");

                    b.HasKey("TurnoId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PrestazioneId");

                    b.ToTable("Turni");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Paziente", "Paziente")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Fattura", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Paziente", "Paziente")
                        .WithMany("Fatture")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithOne("Fattura")
                        .HasForeignKey("MediCore.Api.Domain.Entities.Fattura", "PrenotazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Medico", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Servizio", "Servizio")
                        .WithMany("Medici")
                        .HasForeignKey("ServizioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", "User")
                        .WithOne("Medico")
                        .HasForeignKey("MediCore.Api.Domain.Entities.Medico", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servizio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Notifica", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Paziente", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", "User")
                        .WithOne("Paziente")
                        .HasForeignKey("MediCore.Api.Domain.Entities.Paziente", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prenotazione", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Paziente", "Paziente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prescrizione", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Medico", "Medico")
                        .WithMany("Prescrizioni")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.Paziente", "Paziente")
                        .WithMany("Prescrizioni")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prestazione", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Servizio", "Servizio")
                        .WithMany("Prestazioni")
                        .HasForeignKey("ServizioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servizio");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Referto", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithOne("Referto")
                        .HasForeignKey("MediCore.Api.Domain.Entities.Referto", "PrenotazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.RigaPrescrizione", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Prescrizione", "Prescrizione")
                        .WithMany("Righe")
                        .HasForeignKey("PrescrizioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescrizione");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Slot", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Turno", "Turno")
                        .WithMany("Slot")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Tariffa", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Prestazione", "Prestazione")
                        .WithMany("Tariffe")
                        .HasForeignKey("PrestazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestazione");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Turno", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.Medico", "Medico")
                        .WithMany("Turni")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.Prestazione", "Prestazione")
                        .WithMany("Turni")
                        .HasForeignKey("PrestazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Prestazione");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MediCore.Api.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Prescrizioni");

                    b.Navigation("Turni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Paziente", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Fatture");

                    b.Navigation("Prenotazioni");

                    b.Navigation("Prescrizioni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prenotazione", b =>
                {
                    b.Navigation("Fattura");

                    b.Navigation("Referto");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prescrizione", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Prestazione", b =>
                {
                    b.Navigation("Tariffe");

                    b.Navigation("Turni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Servizio", b =>
                {
                    b.Navigation("Medici");

                    b.Navigation("Prestazioni");
                });

            modelBuilder.Entity("MediCore.Api.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Slot");
                });
#pragma warning restore 612, 618
        }
    }
}
